### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by OneCricketeer** [paspao/kafka-in-one-container#1]
Thanks for putting this together, but can it be more configurable?

For example, how can you edit the heap sizes of Zookeeper and Kafka? 

---

Can it be smaller? You don't need to package the windows/ folder or any other property files than Zookeeper and server properties. Nor the site-docs 

---

Also, what's wrong using two services via Docker Compose like existing Kafka images require?

**Comment by paspao** [comment]
Yes it can be more configurable mounting volumes on configuration files, but this is only an example on how to put together 2 processes in one container.

---

Yes it can be smaller deleting the windows and site-docs folders.

---

Nothing is wrong using two services via docker-compose, but in some context (experimental or fast development context) you need something more light. I don't recommend to use this configuration in a production environment.

**Comment by OneCricketeer** [comment]
What are your opinions on [`lensesio/fast-data-dev`](https://github.com/lensesio/fast-data-dev)?

**Comment by paspao** [comment]
> What are your opinions on [`lensesio/fast-data-dev`](https://github.com/lensesio/fast-data-dev)?

It's a great solution, I only showed you how to run multiple processes in one container

**Comment by OneCricketeer** [comment]
And thanks for that, but why Kafka

The docs already address how to do what you've shown, no? 
https://docs.docker.com/config/containers/multi-service_container/

**Comment by paspao** [comment]
> And thanks for that, but why Kafka
> 
> The docs already address how to do what you've shown, no?
> https://docs.docker.com/config/containers/multi-service_container/

Yes of course, I added more details
